### ISSUE TITLE
GE binary on Debian is called googleearth instead of google-earth

### ISSUE THREAD

**Issue by rduivenvoorde** [nextgis/send2google_earth#2]
After installing GE in Debian testing using the 'googleeath-package' package, the binary is called googleearth, while the plugin calls for google-earth in current version.

Off course easy to fix by either fixing the python, or adding a symbolic link. But I think the plugin could just try both options (via a try catch)?

**Comment by simgislab** [comment]
fixed that in new release

QIS shouldn't be frozen anymore when GE is opened in linux
