### ISSUE TITLE
Rubberband

### ISSUE THREAD

**Issue by Zeddikus** [nextgis/send2google_earth#6]
При создании нового полигона мне важно видеть то, что будет находиться внутри отрисовываемого полигона, причём в спектрально неискажённом виде. Rubberband позволяет делать создаваемый полигон прозрачным, но при этом столь же прозрачной становится линия, оконтуривающая новый создаваемый полигон - при этом не видно уже созданные границы нового полигона. Было бы значительно более удобнее, если разделить прозрачность области rubberband'а, и линии, оконтуривающей создаваемый полигон. Мне было бы достаточно иметь полностью прозрачный rubberband и полностью непрозрачную линию, оконтуривающую rubberband.

**Comment by simgislab** [comment]
мне кажется ты не туда отправил ишью
